// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.socialathlete.domain;

import com.socialathlete.domain.SAAccountType;

privileged aspect SAAccountType_Roo_JavaBean {
    
    public String SAAccountType.getPlatform() {
        return this.platform;
    }
    
    public void SAAccountType.setPlatform(String platform) {
        this.platform = platform;
    }
    
}
