// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.socialathlete.domain;

import com.socialathlete.domain.SALeague;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SALeague_Roo_Configurable {
    
    declare @type: SALeague: @Configurable;
    
}
