// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.socialathlete.domain;

import com.socialathlete.domain.SALeague;

privileged aspect SALeague_Roo_JavaBean {
    
    public String SALeague.getLeagueName() {
        return this.leagueName;
    }
    
    public void SALeague.setLeagueName(String leagueName) {
        this.leagueName = leagueName;
    }
    
}
